import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'getting-started',
    'architecture',
    'cypher-compatibility',
    'api',
    'tech-stack',
    'acid-guarantees',
    {
      type: 'category',
      label: 'Web Visualizer',
      items: ['visualizer/index'],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Architecture Decision Records',
      items: [
        {type: 'autogenerated', dirName: 'adr'},
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Performance',
      items: [
        {type: 'autogenerated', dirName: 'performance'},
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'LDBC Benchmarks',
      items: [
        {type: 'autogenerated', dirName: 'ldbc'},
      ],
      collapsed: true,
    },
    'glossary',
  ],
};

export default sidebars;
