import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'getting-started',
    {
      type: 'category',
      label: 'Installation',
      items: ['installation/docker', 'installation/binary', 'installation/source', 'installation/configuration'],
    },
    {
      type: 'category',
      label: 'Cypher Guide',
      items: ['cypher/basics', 'cypher/crud', 'cypher/patterns', 'cypher/aggregations', 'cypher/functions'],
    },
    {
      type: 'category',
      label: 'Administration',
      items: ['admin/authentication', 'admin/multi-tenancy', 'admin/backup-restore', 'admin/monitoring'],
    },
    {
      type: 'category',
      label: 'SDKs & Drivers',
      items: ['sdks/index', 'sdks/rust', 'sdks/python', 'sdks/typescript', 'sdks/rest-api', 'sdks/resp-protocol'],
    },
    {
      type: 'category',
      label: 'Web Visualizer',
      items: ['visualizer/index', 'visualizer/features'],
    },
    {
      type: 'category',
      label: 'Advanced',
      items: ['advanced/vector-search', 'advanced/algorithms', 'advanced/nlq', 'advanced/architecture'],
    },
    {
      type: 'category',
      label: 'Architecture Decision Records',
      items: [
        {type: 'autogenerated', dirName: 'adr'},
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Performance',
      items: [
        {type: 'autogenerated', dirName: 'performance'},
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'LDBC Benchmarks',
      items: [
        {type: 'autogenerated', dirName: 'ldbc'},
      ],
      collapsed: true,
    },
    'glossary',
  ],
};

export default sidebars;
