export const CYPHER_KEYWORDS: string[] = [
  "MATCH",
  "RETURN",
  "WHERE",
  "CREATE",
  "DELETE",
  "SET",
  "REMOVE",
  "MERGE",
  "WITH",
  "UNWIND",
  "UNION",
  "UNION ALL",
  "CALL",
  "FOREACH",
  "ORDER BY",
  "SKIP",
  "LIMIT",
  "EXPLAIN",
  "PROFILE",
  "OPTIONAL MATCH",
  "DETACH DELETE",
  "ON CREATE SET",
  "ON MATCH SET",
  "DISTINCT",
  "AS",
  "AND",
  "OR",
  "NOT",
  "XOR",
  "IN",
  "IS NULL",
  "IS NOT NULL",
  "STARTS WITH",
  "ENDS WITH",
  "CONTAINS",
  "TRUE",
  "FALSE",
  "NULL",
  "CASE",
  "WHEN",
  "THEN",
  "ELSE",
  "END",
  "EXISTS",
  "YIELD",
  "ASC",
  "ASCENDING",
  "DESC",
  "DESCENDING",
  "ALL",
  "FILTER",
  "REDUCE",
  "FOR",
  "ON",
  // SEARCH clause (vector search within MATCH)
  "SEARCH",
  "SCORE",
  "VECTOR INDEX",
  // Schema commands
  "SHOW INDEXES",
  "SHOW VECTOR INDEXES",
  "SHOW VECTOR INDEX",
  "SHOW CONSTRAINTS",
  "CREATE INDEX",
  "DROP INDEX",
  "DROP CONSTRAINT",
  "CREATE CONSTRAINT",
  "CREATE VECTOR INDEX",
  "IF NOT EXISTS",
  "IF EXISTS",
  "OPTIONS",
];

export const CYPHER_FUNCTIONS: string[] = [
  // String functions
  "toUpper",
  "toLower",
  "trim",
  "ltrim",
  "rtrim",
  "replace",
  "substring",
  "left",
  "right",
  "reverse",
  "split",
  "toString",
  "toInteger",
  "toFloat",
  "toBoolean",
  // Math functions
  "abs",
  "ceil",
  "floor",
  "round",
  "sqrt",
  "sign",
  "log",
  "exp",
  "rand",
  // Collection functions
  "size",
  "length",
  "head",
  "last",
  "tail",
  "range",
  "keys",
  "collect",
  "properties",
  // Graph functions
  "id",
  "labels",
  "type",
  "startNode",
  "endNode",
  "nodes",
  "relationships",
  // Utility functions
  "coalesce",
  "exists",
  "randomUUID",
  // Aggregation functions
  "count",
  "sum",
  "avg",
  "min",
  "max",
  // Date/time functions
  "date",
  "datetime",
  "localDatetime",
  "localTime",
  "time",
  "duration",
  "duration.between",
  "timestamp",
  // Predicate functions
  "all",
  "any",
  "none",
  "single",
];

export const CYPHER_PROCEDURES: string[] = [
  "algo.pageRank",
  "algo.wcc",
  "algo.scc",
  "algo.bfs",
  "algo.dijkstra",
  "algo.shortestPath",
  "algo.weightedPath",
  "algo.maxFlow",
  "algo.mst",
  "algo.triangleCount",
  "algo.or.solve",
  "db.index.vector.queryNodes",
];
